services:
        
    settings.command.installer:
        class: Gekomod\SettingsBundle\Command\SettingsInstallerCommand
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: 'console.command', command: 'settings:install' }

    admin.settings_new:
        class: Gekomod\SettingsBundle\Admin\SettingsAdmin
        arguments:
            - ~
            - ~
            - Gekomod\SettingsBundle\Controller\SettingsopCRUDController
        tags:
            - { name:  sonata.admin, manager_type: orm, group: Ustawienia, label: Ustawienia}
            
    gekomod_settings.form.type.settings:
        class: Gekomod\SettingsBundle\Form\SettingsType
        arguments: ["@doctrine.orm.entity_manager"]

    myproject.twig.toolbox_extension:
        class: Gekomod\SettingsBundle\Twig\PathExtension
        # Inject doctrine as first parameter
        arguments:
          ["@doctrine","@service_container","@twig.loader.filesystem"]
        tags:
          -  { name: twig.extension }

    settings.new:
        class: Gekomod\SettingsBundle\Service\Settings_Get
        arguments:
          ["@doctrine"]
        public: true
    _defaults: { public: false, autowire: true, autoconfigure: true }
    Gekomod\SettingsBundle\Controller\:
        resource: '%kernel.project_dir%/vendor/gekomod/settings-bundle/Controller'
        autowire: true
        tags: ['controller.service_arguments']

    kernel.listener.debug_listener:
        class: Gekomod\SettingsBundle\EventListener\DebugListener
        arguments:
            ["@service_container","@doctrine","@twig.loader"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            
    kernel.listener.seo_listener:
        class: Gekomod\SettingsBundle\EventListener\SeoListener
        arguments:
            ["@service_container","@doctrine"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
